### ISSUE TITLE
ifttt key nicht erlaubt - da kein Bindestrich

### ISSUE THREAD

**Issue by seiya74656** [Der-Henning/tgtg-notifications#1]
Tolles Projekt! Email Funktioniert, es scheint so als ob der ifttt push nicht klappt - im API Key ist der bindestrich nicht erlaubt ist (siehe Fehlermeldung), dieser gehört jedoch zum Key dazu (ebenfalls im Bild). Die Events werden leider nicht getriggert.

![ifttt](https://user-images.githubusercontent.com/6532637/115097352-d6bb3280-9f29-11eb-9943-8db5289dbb72.png)

![ifttt2](https://user-images.githubusercontent.com/6532637/115097371-04a07700-9f2a-11eb-9df5-ffd8c53316df.png)

**Comment by Der-Henning** [comment]
Danke für den Hinweis! Das Problem sollte jetzt behoben sein.
