### ISSUE TITLE
tgtg website not working

### ISSUE THREAD

**Issue by eddyhuang97** [Der-Henning/tgtg-notifications#2]
Hello, the website seems to be down right now. Would you mind taking a quick look at it? Thank you for your website it has been super helpful.

**Comment by Der-Henning** [comment]
Unfortunately I currently have a problem with my provider. The technical support is working on a solution. I hope i will be back online today. Then the service should be available again as usual.

I am currently running the website on my private hardware. This is the only way I can provide the service free of charge. I could only bear the costs for a professional provider via an appropriate payment model (or sufficient donations) and I would like to avoid that at the moment.

**Comment by Der-Henning** [comment]
I am back online !
